version: 0.2

env:
  variables:
    AWS_REGION: "REGION"
    ECR_REPO_NAME: "ECR_REPO_NAME"
    AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:lastest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:lastest
artifacts:
  files:
    - appspec.yml
    - scripts/AfterInstall.sh
    - scripts/ApplicationStart.sh
    - scripts/ApplicationStop.sh
